version: 0.0
os: linux
files:
  - source: /teampass/
    destination: /home/ec2-user/app
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 100
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 180
      runas: root
  ValidateService:
    - location: scripts/app_start.sh
      timeout: 300
      runas: root